apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../base/

images:
 - name: szaffarano/argocd-sandbox
   newTag: v0.1.5

patches:
  - target:
      kind: Ingress
      name: server-ingress
    patch: |
      - op: replace
        path: /metadata/namespace
        value: production
      - op: replace
        path: /spec/rules/0/host
        value: production.local
