version: "3"
services:
  go:
    image: szaffarano/go-builder:1
    volumes:
      - $PWD:/src
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /src
    environment:
      HOME: "/tmp/home"
      GOPATH: "/tmp/home/go"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      DOCKERHUB_TOKEN: "${DOCKERHUB_TOKEN}"
      DOCKERHUB_USERNAME: "${DOCKERHUB_USERNAME}"
      BUILDKITE_TAG: "${BUILDKITE_TAG}"
      GIT_COMMIT: "${GIT_COMMIT}"
      VERSION: "${VERSION}"
      IMAGE: "${IMAGE}"
