steps:
  - label: ":eyeglasses: Lint"
    command: ".buildkite/scripts/lint.sh"
    if: |
      build.tag !~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/
    plugins:
      - docker-compose#v4.14.0:
          run: rust
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          propagate-uid-gid: true
          env:
            - GITHUB_TOKEN

  - label: ":hammer: Build"
    command: ".buildkite/scripts/build.sh"
    key: build
    if: |
      build.tag !~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/
    plugins:
      - docker-compose#v4.14.0:
          run: rust
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          propagate-uid-gid: true
          env:
            - GITHUB_TOKEN

  - label: ":test_tube: Test"
    command: ".buildkite/scripts/test.sh"
    key: test
    depends_on: build
    if: |
      build.tag !~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/
    plugins:
      - docker-compose#v4.14.0:
          run: rust
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          propagate-uid-gid: true
          env:
            - GITHUB_TOKEN

  - label: ":rocket: Publish"
    command: ".buildkite/scripts/deploy.sh"
    key: deploy
    depends_on: test
    if: |
      build.tag !~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/ &&
      build.branch == "main"
    plugins:
      - docker-compose#v4.14.0:
          run: rust
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          propagate-uid-gid: true
          env:
            - GITHUB_TOKEN

  - label: ":rocket: Release :the_horns:"
    command: ".buildkite/scripts/release.sh"
    depends_on: deploy
    if: |
      build.tag =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\$/
    plugins:
      - docker-compose#v4.14.0:
          run: rust
          config: .buildkite/docker-compose.yaml
          cli-version: 2
          propagate-uid-gid: true
          env:
            - GITHUB_TOKEN
