apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../base/

images:
 - name: szaffarano/argocd-sandbox
   newTag: latest

patches:
  - target:
      kind: Ingress
      name: server-ingress
    patch: |
      - op: replace
        path: /metadata/namespace
        value: staging
      - op: replace
        path: /spec/rules/0/host
        value: staging.local
