#!/usr/bin/env bash

set -eo pipefail

function main {
  ensure_home
  configure_git
  setup_docker_env

  GIT_COMMIT="$(git_revision)"
  VERSION="$(app_version)"
  IMAGE="szaffarano/argocd-sandbox"

  export GIT_COMMIT
  export VERSION
  export IMAGE
}

function ensure_home {
  [ -d "$HOME" ] || mkdir "$HOME"
}

function configure_git {
  git config --global --add safe.directory "$(pwd)"
  git config --global user.email "no-reply@ci-bot"
  git config --global user.name "CI Bot"

  # TODO: configure gpg key to sign commits
}

function git_revision {
  git rev-parse --short HEAD
}

function app_version {
  if [ -n "${BUILDKITE_TAG:-}" ]; then
    echo "$BUILDKITE_TAG"
  else
    echo "$(git_revision)-dev"
  fi
}

function setup_docker_env {
  echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
}

main "$@"
